steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - --entry-point=pub_sub_trigger
  - --source=https://source.developers.google.com/projects/defence-blocklist-updater/repos/github_defenceapp_defenceblocklistupdater/moveable-aliases/master/paths/
  - blocklist-updater
